---
homebrew_packages:
  - group: provisioning
    pkgs:
      - name: ansible
  - group: text utils
    pkgs:
      - name: clang-format
  - group: git
    pkgs:
      - name: ghq
      - name: git
      - name: hub
      - name: tig
  - group: net utils
    pkgs:
      - name: curl
      - name: wget
  - group: db utils
    pkgs:
      - name: sqlite
  - group: lang
    pkgs:
      - name: go
  - group: build tools
    pkgs:
      - name: autoconf
      - name: automake
      - name: bison
      - name: cmake
      - name: gcc
      - name: libtool
      - name: make
      - name: makedepend
      - name: pkg-config
  - group: debug tools
    pkgs:
      - name: cgdb
      - name: gdb

homebrew_cask_apps:
  - appcleaner
  - avira-antivirus
  - box-sync
  - db-browser-for-sqlite
  - dropbox
  - karabiner-elements
  - kawasemi
  - onyx
  - virtualbox
  - xquartz
